- include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: make docker configuration directory
  file:
    state: directory
    name: /etc/docker

- name: Install docker storage configuration
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Allow routing via loopback interface
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    reload: yes
