- name: get certificate facts
  aws_acm_facts:
    name: "{{ cloudfront_certificate_name }}"
    profile: "{{ profile|default(omit) }}"
    region: "us-east-1"
  register: cert

- name: set certificate_arn fact
  set_fact:
    certificate_arn: "{{ cert.certificates[0].certificate_arn }}"
  when: cert.certificates|length == 1

- name: get web acl id
  aws_waf_facts:
    name: "{{ cloudfront_waf }}"
    profile: "{{ profile|default(omit) }}"
  register: web_acl
  when: cloudfront_waf is defined

- name: set web_acl_id fact
  set_fact:
    web_acl_id: "{{ web_acl.wafs[0].web_acl_id }}"
  when:
    - not web_acl.skipped|default(False)
    - web_acl.wafs|length == 1

- name: create custom error responses parameter
  set_fact:
    cloudfront_custom_error_responses: >
      {{ cloudfront_custom_error_responses + [
           { 'error_code': item,
             'response_page_path': cloudfront_errors.pages[item]|default(cloudfront_errors.pages.default),
             'response_code': ((cloudfront_errors.responses|default({}))[item])|default(item),
             'error_caching_min_ttl': cloudfront_errors.ttl
           } ] }}
  with_items: "{{ cloudfront_errors.codes|default([]) }}"

- name: debug
  debug:
    var: item
  with_items:
    - "{{ cloudfront_origins }}"
    - "{{ cloudfront_custom_error_responses }}"
    - "{{ cloudfront_logging }}"
    - "{{ cloudfront_certificate|default('') }}"
    - "{{ web_acl_id|default('') }}"

- name: create cloudfront distribution
  cloudfront_distribution:
    state: present
    alias: "{{ cloudfront_alias }}"
    aliases: "{{ cloudfront_aliases|default(omit) }}"
    purge_aliases: yes
    origins: "{{ cloudfront_origins }}"
    purge_origins: yes
    logging: "{{ cloudfront_logging }}"
    viewer_certificate: "{{ cloudfront_certificate|default(omit) }}"
    web_acl_id: "{{ web_acl_id|default(omit) }}"
    custom_error_responses: "{{ cloudfront_custom_error_responses }}"
    purge_custom_error_responses: yes
    default_cache_behavior: "{{ cloudfront_default_cache_behavior }}"
    default_root_object: "{{ cloudfront_default_root_object|default(omit) }}"
    cache_behaviors: "{{ cloudfront_cache_behaviors }}"
    purge_cache_behaviors: yes
    ipv6_enabled: "{{ cloudfront_ipv6_enabled }}"
    profile: "{{ profile|default(omit) }}"
  register: cloudfront_distribution

- name: ensure DNS points at cloudfront for cloudfront_alias
  route53:
    zone: "{{ cloudfront_alias|regex_replace('^[^.]*\\.', '') }}"
    record: "{{ cloudfront_alias }}"
    value: "{{ cloudfront_distribution.domain_name }}"
    type: CNAME
    overwrite: yes
    state: present
    profile: "{{ profile|default(omit) }}"
  when: cloudfront_dns

- name: ensure DNS points at cloudfront for cloudfront_aliases
  route53:
    zone: "{{ item|regex_replace('^[^.]*\\.', '') }}"
    record: "{{ item }}"
    value: "{{ cloudfront_distribution.domain_name }}"
    type: CNAME
    overwrite: yes
    state: present
    profile: "{{ profile|default(omit) }}"
  with_items: "{{ cloudfront_aliases }}"
  when: cloudfront_dns
